mongo:
  # Single Cluster Settings
  host: "127.0.0.1"
  port: 27017

  # Multiple Cluster Settings
  #hosts:
  #  - host: "127.0.0.1"
  #    port: 27017
  #  - host: cluster2
  #    port: 28000

  # database
  db_name: argon

  #replicaSet: "foo"
  #serverSelectionTimeoutMS: 30000

  # Connection Pool Settings
  #maxPoolSize: 50
  #minPoolSize: 25
  #maxIdleTimeMS: 300000
  #maxLifeTimeMS: 3600000
  #waitQueueMultiple: 10
  #waitQueueTimeoutMS: 10000
  #maintenanceFrequencyMS: 2000
  #maintenanceInitialDelayMS: 500

  # Credentials / Auth
  username: root
  password: example
  authSource: admin

  # Auth mechanism
  #authMechanism: GSSAPI
  #gssapiServiceName: myservicename

  # Socket Settings
  #connectTimeoutMS: 300000
  #socketTimeoutMS: 100000
  #sendBufferSize: 8192
  #receiveBufferSize: 8192
  #keepAlive: true

  # Heartbeat socket settings
  #"heartbeat.socket":
  #  connectTimeoutMS: 300000
  #  socketTimeoutMS: 100000
  #  sendBufferSize: 8192
  #  receiveBufferSize: 8192
  #  keepAlive: true

  # Server Settings
  #heartbeatFrequencyMS: 1000
  #minHeartbeatFrequencyMS: 500